config/routes.rb
Todos::Application.routes.draw do
  resources :todos do
    get :checked, on: :member
  end
  
  root 'todos#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates_presence_of :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :checked]
  
  before_action :get_todos

  def index
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    
    if @todo.save
      redirect_to todos_path, notice: 'Todo was successfully created.'
    else
      redirect_to :back, alert: "Your todo content is empty."
    end
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path, notice: 'Todo was successfully updated.'
    else
      redirect_to :back, alert: "Your todo content is empty."
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_url, notice: "Todo was successfully deleted."
  end

  def get_todos
    @todos = Todo.order(:created_at).reverse_order
  end
  
  def checked
    @todo.checked == true ? @todo.update_attribute(:checked, false) : @todo.update_attribute(:checked, true)
    redirect_to :back, notice: "Todo status was changed."
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:content, :checked)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    new_content = RedCloth.new(content).to_html
  end
  
  def set_title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page-header">
  <h1><%= yield(:title) %></h1>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag(:div, '<button type="button" class="close" data-dismiss="alert">&times;</button>'.html_safe + raw(msg), id: "flash_#{name}", class: "alert alert-#{name}") %>
<% end %>

<%= yield %>

<table class="table table-hover table-bordered">
  <%= render @todos %>
</table>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <%= f.text_area :content, style: "width: 480px; height: 100px;" %>
  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to("View all todos", root_path, class: "btn pull-right") unless @todo.new_record? %>
<% end %>

app/views/todos/_todo.html.erb
<tr>
  <td>
    <span class="pull-right">
      <%= link_to "<i class='icon-star#{'-empty' if todo.checked == false}'></i>".html_safe, checked_todo_path(todo), class: "btn btn-mini" %>
      <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_todo_path(todo), class: "btn btn-mini" %>
      <%= link_to '<i class="icon-trash icon-white"></i>'.html_safe, todo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %>
    </span>
    
    <%= markdown(todo.content).html_safe %>
  </td>
</tr>

app/views/todos/edit.html.erb
<% set_title "Edit todo" %>

<%= render "todos/form" %>

app/views/todos/index.html.erb
<% set_title "Todos" %>

<%= render "todos/form" %>